/* import { BaseLayout } from "@/components/shared";
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Dashboard | Главная',
};

export default async function DashboardLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;

    return <BaseLayout locale={locale}>{children}</BaseLayout>;
}


 */

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            DASHBOARD HEADER
            <body>{children}</body>
        </html>
    );
}
